import React from 'react';

interface GuestDetailsScreenProps {
  accessCode?: string;
  codeGeneratedBy?: string;
  codeGeneratedFor?: string;
  guestFeatures?: string;
  guestCategory?: string;
  date?: string;
  address?: string;
  codeType?: string;
  codeExpiry?: string;
  mode?: 'check-in' | 'check-out';
  confirmButtonText?: string;
  onAllow?: () => void;
  onDeny?: () => void;
}

export const GuestDetailsScreen: React.FC<GuestDetailsScreenProps> = ({
  accessCode = '005UHJ9',
  codeGeneratedBy = 'Teni Olayiwola',
  codeGeneratedFor = 'Kamsy Okafor',
  guestFeatures = 'Black Honda',
  guestCategory = 'Electrician',
  date = '08/08/2023',
  address = 'House 8 Pari Street',
  codeType = 'One time entry',
  codeExpiry = '05:00 pm',
  mode = 'check-in',
  confirmButtonText,
  onAllow,
  onDeny,
}) => {
  const primaryButtonText =
    confirmButtonText || (mode === 'check-out' ? 'Confirm exit' : 'Allow');

  return (
    <div style={styles.mobileShell}>
      <div style={styles.container}>
        {/* Header Logo */}
        <div style={styles.header}>
          <div style={styles.logoRow}>
            <svg
              width="36"
              height="40"
              viewBox="0 0 48 46"
              fill="none"
              xmlns="http://www.w3.org/2000/svg"
              style={{ flexShrink: 0 }}
            >
              <path
                fill="#347357"
                d="M25.946 44.938c-.664.845-2.021.375-2.021-.698V33.937a2.26 2.26 0 0 0-2.262-2.262H10.287c-.92 0-1.456-1.04-.92-1.788l7.48-10.471c1.07-1.497 0-3.578-1.842-3.578H1.237c-.92 0-1.456-1.04-.92-1.788L10.013.474c.214-.297.556-.474.92-.474h28.894c.92 0 1.456 1.04.92 1.788l-7.48 10.471c-1.07 1.498 0 3.579 1.842 3.579h11.377c.943 0 1.473 1.088.89 1.83L25.947 44.94z"
              />
            </svg>
            <span style={styles.logoText}>GateShark</span>
          </div>
        </div>

        {/* Guest Details Content */}
        <div style={styles.detailsContainer}>
          <h1 style={styles.detailsTitle}>Guest Details</h1>

          <div style={styles.detailsList}>
            <div style={styles.detailRow}>
              <span style={styles.detailLabel}>Access code:</span>
              <span style={{ ...styles.detailValue, color: '#00a651' }}>
                {accessCode}
              </span>
            </div>

            <div style={styles.detailRow}>
              <span style={styles.detailLabel}>Code generated by:</span>
              <span style={styles.detailValue}>{codeGeneratedBy}</span>
            </div>

            <div style={styles.detailRow}>
              <span style={styles.detailLabel}>Code generated for:</span>
              <span style={styles.detailValue}>{codeGeneratedFor}</span>
            </div>

            <div style={styles.detailRow}>
              <span style={styles.detailLabel}>Guest features:</span>
              <span style={styles.detailValue}>{guestFeatures}</span>
            </div>

            <div style={styles.detailRow}>
              <span style={styles.detailLabel}>Guest category:</span>
              <span style={styles.detailValue}>{guestCategory}</span>
            </div>

            <div style={styles.detailRow}>
              <span style={styles.detailLabel}>Date:</span>
              <span style={styles.detailValue}>{date}</span>
            </div>

            <div style={styles.detailRow}>
              <span style={styles.detailLabel}>Address:</span>
              <span style={styles.detailValue}>{address}</span>
            </div>

            <div style={styles.detailRow}>
              <span style={styles.detailLabel}>Code type:</span>
              <span style={{ ...styles.detailValue, color: '#00a651' }}>
                {codeType}
              </span>
            </div>

            <div style={{ ...styles.detailRow, borderBottom: 'none' }}>
              <span style={styles.detailLabel}>Code expiry:</span>
              <span style={styles.detailValue}>{codeExpiry}</span>
            </div>
          </div>

          {/* Action Buttons */}
          <div style={styles.detailsActionRow}>
            <button type="button" onClick={onDeny} style={styles.denyBtn}>
              Deny
            </button>
            <button type="button" onClick={onAllow} style={styles.allowBtn}>
              {primaryButtonText}
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};

const styles: Record<string, React.CSSProperties> = {
  mobileShell: {
    width: '100%',
    minHeight: '100vh',
    backgroundColor: '#f8fafc',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'flex-start',
    fontFamily: "'Montserrat', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
    overflowY: 'auto',
  },
  container: {
    width: '100%',
    maxWidth: '430px',
    minHeight: '100vh',
    padding: 'calc(24px + env(safe-area-inset-top, 0px)) 24px calc(36px + env(safe-area-inset-bottom, 0px))',
    boxSizing: 'border-box',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    backgroundColor: '#ffffff',
    boxShadow: '0 10px 30px rgba(0, 0, 0, 0.04)',
    position: 'relative',
  },
  header: {
    width: '100%',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: '8px',
    marginBottom: '20px',
  },
  logoRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
  },
  logoText: {
    fontSize: '24px',
    fontWeight: 800,
    color: '#2d3748',
    letterSpacing: '-0.4px',
  },
  detailsContainer: {
    width: '100%',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    flex: 1,
  },
  detailsTitle: {
    fontSize: '22px',
    fontWeight: 700,
    color: '#0f172a',
    margin: '12px 0 32px 0',
    textAlign: 'center',
  },
  detailsList: {
    width: '100%',
    display: 'flex',
    flexDirection: 'column',
    marginBottom: '40px',
  },
  detailRow: {
    width: '100%',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '14px 0',
    borderBottom: '1px solid #e2e8f0',
    fontSize: '15px',
  },
  detailLabel: {
    color: '#475569',
    fontWeight: 400,
  },
  detailValue: {
    fontWeight: 700,
    color: '#0f172a',
  },
  detailsActionRow: {
    width: '100%',
    display: 'flex',
    gap: '16px',
    marginTop: 'auto',
    paddingBottom: '12px',
  },
  denyBtn: {
    flex: 1,
    height: '52px',
    borderRadius: '12px',
    border: '1.5px solid #dc2626',
    backgroundColor: '#ffffff',
    color: '#dc2626',
    fontSize: '17px',
    fontWeight: 700,
    cursor: 'pointer',
  },
  allowBtn: {
    flex: 1,
    height: '52px',
    borderRadius: '12px',
    border: 'none',
    backgroundColor: '#347357',
    color: '#ffffff',
    fontSize: '17px',
    fontWeight: 700,
    cursor: 'pointer',
    boxShadow: '0 4px 12px rgba(52, 115, 87, 0.25)',
  },
};
